### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [Instand/SolarSystem#7]
[An extra null pointer check is not needed in a function](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like [the destructor for the class “SolarSystem::Object3DContainer”](https://github.com/Instand/SolarSystem/blob/1ccd33de84d4bc9f761b57de9d600d541ab6254e/Core/object3dcontainer.cpp#L25 "Update candidate").

**Comment by Instand** [comment]
Fixed, thanks
https://github.com/Instand/SolarSystem/commit/95e58223f163e2df7000f42657c61d10a10073f8

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Instand/SolarSystem/commit/95e58223f163e2df7000f42657c61d10a10073f8 "Deletion of a redundant check").
